// <auto-generated />
using System.Collections.Generic;
using FHIR_NEW.Data_Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FHIR_NEW.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240822050913_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FHIR_NEW.Data_Access.PatientModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Communication")
                        .HasColumnType("text");

                    b.Property<List<string>>("Deceased")
                        .HasColumnType("text[]");

                    b.Property<string>("DoB")
                        .HasColumnType("text");

                    b.Property<List<string>>("Family_ContactDetails")
                        .HasColumnType("text[]");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<List<string>>("MaritalStatus")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("MultipleBirth")
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<List<string>>("Telecom")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("PatientsDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
